## MySQL Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coredb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: true
        format_sql: true

springdoc:
  swagger-ui:
    path: /
    operationsSorter: method
