# This is a basic workflow to help you get started with Actions

name: Kotlin Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "gadgetgallery" ]
  pull_request:
    branches: [ "gadgetgallery" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
        with:
          script: |
              #!/usr/bin/env kotlin
      - run: kotlinc src/main/kotlin/com/tek/gadgetgallery/GadgetgalleryApplication.kt -include-runtime -d /tmp/gadgetgallery.jar; java -jar /tmp/gadgetgallery.jar
